# -*- coding: utf-8 -*-
"""ETL y Clusterización de  Empresas del S&P 500

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHch1VtI5KHB2HFHPH3Z5gSBfLPt-mbU
"""

!pip install pandas numpy matplotlib seaborn scikit-learn

from google.colab import files

uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['S&P500_prices.csv']))
print(df)

df['Date'] = pd.to_datetime(df.Date)
print(df)

df = df.sort_values(by=['Ticker', 'Date'], ascending=True)
print(df)

df['Return'] = df.groupby('Ticker')['Close'].pct_change()*100
print(df)

df.fillna(0, inplace=True)
print(df)

std_df = df.groupby('Ticker')['Return'].std()
print(std_df)

range_df = df.groupby('Ticker')['Return'].max()
range_df -= df.groupby('Ticker')['Return'].min()
print(range_df)

metrics_df = pd.concat([std_df, range_df], axis=1)
metrics_df.columns = ["SD", "Range"]
print(metrics_df)

print(metrics_df.head())

metrics_df = metrics_df.drop(index=metrics_df.index[0])
print(metrics_df)



# Min-Max Normalization
df_norm = (metrics_df-metrics_df.min())/(metrics_df.max()-metrics_df.min())
print(df_norm)

from matplotlib import pyplot as plt

X = np.array(df_norm['SD'])
Y = np.array(df_norm['Range'])
plt.scatter(X, Y)

from sklearn.cluster import KMeans

k=3
k_means = KMeans(n_clusters=k)
clusters = k_means.fit_predict(df_norm)
metrics_df['Cluster'] = clusters
Y = np.array(metrics_df['Cluster'])
print(metrics_df)

X = np.array(df_norm)
Y = np.array(metrics_df['Cluster'])
plt.xlabel(
    "Desviación",
    size=10,
)
plt.ylabel(
    "Rango",
    size=10,
)
plt.scatter(X[:,0], X[:,1], c=Y)

"""**Conclusiones: **El ejercicio muestra una tarea de clasifición para las acciones listadas en el listado S&P500 publicado en Yahoo.com, realizado con las métricas de la desviación estándar y el rango de variación del precio de cierre de las acciones, visto en los tre prieros meses del año 2024.

Como se puede ver en la gráfica final, el resultado de la ejecución fue el de generar tres clusters, que agrupan las acciones en las del grupo de abajo a la izquierda que pueden ser clasificados más estables o de menos volatilidad ya que sus métricas de variación están más orientadas al cero.

En el grupo púrpura, en la mitad de la gráfica pueden identificarse las acciones con una volatilidad moderada, y en el cluster amarillo, las acciones de más alta volatilidad según los datos analizados.

Esta información puede ser de utilidad para que un inversionista realice toma de decisiones para nuevas actividades de inversión.

"""

